package com.example.sand.controller;
import com.example.sand.model.BinanceCandlestick;
import com.example.sand.model.JobConfiguration;
import com.example.sand.repository.BinanceCandlestickRepository;
import com.example.sand.repository.JobConfigurationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/v1/candle/binance") // This means URL's start with /demo (after Application path)
public class CandleController {
    @Autowired // This means to get the bean called binanceCandlestickRepository Which is auto-generated by Spring, we will use it to handle the data
    private BinanceCandlestickRepository binanceCandlestickRepository;
    @Autowired
    private JobConfigurationRepository jobConfigurationRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    ResponseEntity<BinanceCandlestick> addNewCandlestick (@RequestBody BinanceCandlestick binanceCandlestick) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        binanceCandlestickRepository.save(binanceCandlestick);
        return ResponseEntity
                .created(URI.create(String.format("/v1/candle/binance/%s", binanceCandlestick.getId())))
                .body(binanceCandlestick);
    }
    
    @PostMapping(path="/addJobConfig") // Map ONLY POST Requests
    public @ResponseBody
    ResponseEntity<JobConfiguration> addNewCandleJobConfig (@RequestBody JobConfiguration jobConfig) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        List<JobConfiguration> jobConfigs = jobConfigurationRepository.getConfigByName(jobConfig.getName());
        //Assumption is we will only have 1 unique name per job
        if(jobConfigs.size()>0){
            for(JobConfiguration job : jobConfigs){
                int res = jobConfigurationRepository.setExistingConfigActive(job.getName());
                if(res==1){
                    return ResponseEntity
                            .created(URI.create(String.format("/v1/candle/binance/%s", jobConfig.getId())))
                            .body(job);
                }else{

                }
            }
        }
        JobConfiguration res = jobConfigurationRepository.save(jobConfig);
        return ResponseEntity
                .created(URI.create(String.format("/v1/candle/binance/%s", jobConfig.getId())))
                .body(res);
    }

    @PostMapping(path="/setJobConfigInactive") // Map ONLY POST Requests
    public @ResponseBody
    ResponseEntity<?> setJobConfigInactive (@RequestBody JobConfiguration jobConfig) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        List<JobConfiguration> jobConfigs = jobConfigurationRepository.getConfigByName(jobConfig.getName());
        //Assumption is we will only have 1 unique name per job
        if(jobConfigs.size()>0){
            for(JobConfiguration job : jobConfigs) {
                int res = jobConfigurationRepository.setExistingConfigNotActive(jobConfig.getName());
                if(res==1){
                    job.setActive(false);
                    return ResponseEntity
                            .status(200).build();
                }else{
                    return ResponseEntity
                            .status(500).build();
                }
            }
        }
        return ResponseEntity.notFound().build();

    }
    
    @GetMapping(path="/getActiveJobCofigs")
    public @ResponseBody
    List<JobConfiguration> getActiveJobCofigs() {
        // This returns a JSON or XML with the users
        return jobConfigurationRepository.getActiveJobConfigs();
    }

    @GetMapping(path="/{id}")
    public @ResponseBody
    Optional<BinanceCandlestick> getCandlestickById(@PathVariable int id) {
        // This returns a JSON or XML with the users
        return binanceCandlestickRepository.findById(id);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<BinanceCandlestick> getAllCandlesticks() {
        // This returns a JSON or XML with the users
        return binanceCandlestickRepository.findAll();
    }

    @GetMapping(path="/getOldestCandlestickByCurrencyPair/{pair}")
    public @ResponseBody BinanceCandlestick getOldestCandlestickByCurrencyPair(@PathVariable String pair) {
        // This returns a JSON or XML with the users
        return binanceCandlestickRepository.getOldestCandlestickByCurrencyPair(pair);
    }
}